/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_AllDiskMeter
#define HEADER_AllDiskMeter
/*
htop - CPUMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int AllDiskMeter_attributes[];

#ifndef MIN
#define MIN(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef MAX
#define MAX(a,b) ((a)>(b)?(a):(b))
#endif


extern MeterClass AllDISKSMeter_class;

#endif
