/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_DiskMeter
#define HEADER_DiskMeter
/*
   htop - DiskMeter.c
   (C) 2004-2011 Hisham H. Muhammad
   Released under the GNU GPL, see the COPYING file
   in the source distribution for its full text.
   */

#include "Meter.h"

extern int DiskMeter_attributes[];



extern MeterClass DiskMeter_class;

extern   MeterClass AllDisksMeter_class;

#endif
